@startuml
!include ../../../../../../../../StylesForDiagrams.puml

package entities as "com.vanskarner.entities"{
    entity MovieBO{
        - id: int
        - title: String
        - image: String
        - backgroundImage: String
        - voteCount: int
        - voteAverage: float
        - releaseDate: String
        - overview: String

        + MovieBO(int, String, String, String, int , float , String , String)
        + isRecommended(): boolean
        ..Getter..
    }
}
@enduml