@startuml
!include ../VanskarnerStyle.puml

title EXPECTATION
package com.vanskarner.cleanmovie{
    class FavoritesPresenter
}
package com.vanskarner.movie{
    interface MovieServices<<interface>>
    class MovieDefaultServices
    interface MovieLocalRepository<<interface>>
    class FindFavoriteMovieUseCase
    class MovieLocalRxRepository

    MovieServices <|.. MovieDefaultServices
    MovieDefaultServices --> FindFavoriteMovieUseCase
    FindFavoriteMovieUseCase --> MovieLocalRepository
    MovieLocalRepository <|.. MovieLocalRxRepository
}

FavoritesPresenter ..> MovieServices

skinparam titleFontColor #green
class MovieDefaultServices classNotVisible
class FindFavoriteMovieUseCase classNotVisible
interface MovieLocalRepository classNotVisible
class MovieLocalRxRepository classNotVisible
hide members
@enduml