@startuml
!include ../../../../../../../architecture_resources/StylesForDiagrams.puml

package cleanmovie as "com.vanskarner.cleanmovie"{

    together {
        class FavoritesPresenter

    }
    together {
        class UpcomingPresenter
    }
    together {
        class UpcomingDetailPresenter
    }
}
package usecases as "com.vanskarner.movie"{
    interface MovieServices<<interface>>
}

FavoritesPresenter .up.> "<<use>>" MovieServices
UpcomingPresenter .up.> "<<use>>" MovieServices
UpcomingDetailPresenter .up.> "<<use>>" MovieServices

hide members
skinparam Linetype ortho
@enduml