@startuml
!include ../../../../../../../StylesForDiagrams.puml

package ui as "com.vanskarner.cleanmovie.ui"{
    class UpcomingPresenter
    class FavoritesPresenter
    class UpcomingDetailPresenter
}
package domain as "com.vanskarner.domain"{
    package movie{
        interface MovieServices<<interface>>
    }
}

MovieServices <.. UpcomingPresenter: <<use>>
MovieServices <.. FavoritesPresenter: <<use>>
MovieServices <.. UpcomingDetailPresenter: <<use>>

hide members
@enduml