@startuml
!include ../../../../../../../architecture_resources/StylesForDiagrams.puml

package cleanmovie as "com.vanskarner.cleanmovie.ui"{
    package errors{
        class ViewErrorFilter
        class ErrorDialog
        interface ErrorView<T><<interface>>
        class FavoritesLimitError
        class NoInternetError
        class NotFoundError
        class ServerError
        class ServiceUnavailableError
        class UnauthorisedError
        class UnknownError
    }
    package movie{
        class MovieDetailModel<<(D,orange)Data Structure>>
        class MovieBasicModel<<(D,orange)Data Structure>>
        class MovieModelMapper
    package favorites{
        interface FavoritesContractView<<interface>>
        interface FavoritesContractPresenter<<interface>>
        class FavoritesFragment
        class FavoritesPresenter
        class DeleteFavoritesDialog
        class FavoritesBindAdapter
        class FavoritesDetailDialog
    }
    package upcoming{
        interface UpcomingContractView<<interface>>
        interface UpcomingContractPresenter<<interface>>
        class UpcomingFragment
        class UpcomingPresenter
        class Pagination
        class RxSearchView
        class UpcomingBindAdapter
    }
    package upcomingDetail{
        interface UpcomingDetailContractView<<interface>>
        interface UpcomingDetailContractPresenter<<interface>>
        class UpcomingDetailFragment
        class UpcomingDetailPresenter
    }
  }
}

ErrorView <|.. FavoritesLimitError
ErrorView <|.. NoInternetError
ErrorView <|.. NotFoundError
ErrorView <|.. ServerError
ErrorView <|.. ServiceUnavailableError
ErrorView <|.. UnauthorisedError
ErrorView <|.. UnknownError
ViewErrorFilter --> "1..*" ErrorView
ViewErrorFilter --> ErrorView
ErrorDialog --> "1" ErrorView
MovieBasicModel <-- MovieDetailModel

/'Favorites Feature'/
FavoritesContractPresenter <|.. FavoritesPresenter
FavoritesContractView <-- FavoritesPresenter
FavoritesPresenter ..> ViewErrorFilter
FavoritesPresenter ..> MovieModelMapper
FavoritesContractView <|.. FavoritesFragment
FavoritesContractPresenter <-- FavoritesFragment
FavoritesFragment --> FavoritesBindAdapter
FavoritesFragment -left-> DeleteFavoritesDialog
FavoritesFragment --> FavoritesDetailDialog
FavoritesFragment ..> ErrorDialog
FavoritesDetailDialog ..> MovieDetailModel

/'Upcoming Feature'/
UpcomingContractPresenter <|.. UpcomingPresenter
UpcomingContractPresenter <-- UpcomingFragment
UpcomingPresenter ..> "0..*" MovieBasicModel
UpcomingPresenter ..> "0..*" MovieBasicModel
UpcomingPresenter ..> ViewErrorFilter
UpcomingPresenter ..> MovieModelMapper
UpcomingContractView <|.. UpcomingFragment
UpcomingContractView <-- UpcomingPresenter
UpcomingFragment --> Pagination
UpcomingFragment --> UpcomingBindAdapter
UpcomingFragment ..> ErrorDialog
UpcomingFragment --> RxSearchView

/'UpcomingDetail Feature'/
UpcomingDetailContractPresenter <|.. UpcomingDetailPresenter
UpcomingDetailContractPresenter <-- UpcomingDetailFragment
UpcomingDetailPresenter ..> MovieModelMapper
UpcomingDetailPresenter ..> ViewErrorFilter
UpcomingDetailContractView <|.. UpcomingDetailFragment
UpcomingDetailContractView <-- UpcomingDetailPresenter
UpcomingDetailFragment ..> ErrorDialog

MovieDetailModel <.. MovieModelMapper
MovieBasicModel <.. MovieModelMapper

hide members
skinparam Linetype ortho
@enduml