@startuml
!include ../../../../../../../StylesForDiagrams.puml

package cleanmovie as "com.vanskarner.cleanmovie.ui"{
package errors {
    class ErrorDialog
    class FavoritesLimitError
    class NoInternetError
    class NotFoundError
    class ServerError
    class ServiceUnavailableError
    class UnauthorisedError
    class UnknownError
}
package movie{
package favorites{
    class FavoritesFragment
}
package upcoming{
    class UpcomingFragment
}
package upcomingDetail{
    class UpcomingDetailFragment
}
}
}
package usecases as "com.vanskarner.movie"{
    package ui{
    package favorites{
        interface FavoritesContractPresenter<<interface>>
        interface FavoritesContractView<<interface>>
    }
    package upcoming{
        interface UpcomingContractPresenter<<interface>>
        interface UpcomingContractView<<interface>>
    }
    package upcomingDetail{
        interface UpcomingDetailContractPresenter<<interface>>
        interface UpcomingDetailContractView<<interface>>
    }
    interface ErrorView<T><<interface>>
    }
}

ErrorView <|.. FavoritesLimitError
ErrorView <|.. NoInternetError
ErrorView <|.. NotFoundError
ErrorView <|.. ServerError
ErrorView <|.. ServiceUnavailableError
ErrorView <|.. UnauthorisedError
ErrorView <|.. UnknownError
ErrorView "1" <.  ErrorDialog: <<use>>


/'Favorites Feature'/
FavoritesContractView <|.. FavoritesFragment
FavoritesContractPresenter <.. FavoritesFragment: <<use>>

/'Upcoming Feature'/
UpcomingContractPresenter <.. UpcomingFragment: <<use>>
UpcomingContractView <|.. UpcomingFragment

/'UpcomingDetail Feature'/
UpcomingDetailContractPresenter <.. UpcomingDetailFragment:<<use>>
UpcomingDetailContractView <|.. UpcomingDetailFragment

hide members
skinparam Linetype ortho
@enduml