@startuml
!include ../../../../../../../architecture_resources/StylesForDiagrams.puml

package cleanmovie as "com.vanskarner.cleanmovie.ui"{
    package movie{
        package favorites {
            class FavoritesPresenter
        }
        package upcoming {
            class UpcomingPresenter
        }
        package upcomingDetail {
            class UpcomingDetailPresenter
        }
    }
}
package usecases as "com.vanskarner.movie"{
    package businesslogic{
    interface MovieServices<<interface>>
    }
}

FavoritesPresenter .up.> MovieServices: <<use>>
UpcomingPresenter .up.> MovieServices: <<use>>
UpcomingDetailPresenter .up.> MovieServices: <<use>>

hide members
skinparam Linetype ortho
@enduml