@startuml
!include ../../StylesForDiagrams.puml

title COMPONENT DIAGRAM WITH MAIN \n Branch: package_by_layer
rectangle domain {
    component UseCases
    component Entities
}
rectangle data {
    component LocalData
    component RemoteData
}
rectangle presentation {
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI       
}
component Main
component Core

presentation ..> Core
data ..> Core
UseCases ..> Core
Main ..> Core
Main .> presentation
Main ..> data
Main ..> UseCases
UseCases .> Entities
RemoteData ..> domain
LocalData ..> domain
FavoritesUI ..> UseCases
UpcomingUI ..> UseCases
UpcomingDetailUI ..> UseCases

skinparam Linetype ortho
@enduml