@startuml
!include ../../StylesForDiagrams.puml

title COMPLEMENTARY COMPONENT DIAGRAM \n Branch: package_by_layer
rectangle domain {
    component UseCases
    component Entities
    interface services

    services -- UseCases
    Entities <. UseCases
}
rectangle "data" {
    component LocalData
    component RemoteData
}
rectangle presentation {   
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI    
}
component core

presentation ..> core
data ..> core
UseCases ..> core

FavoritesUI .> services
UpcomingUI ..> services
UpcomingDetailUI ..> services
RemoteData ..> domain
LocalData ..> domain

skinparam Linetype ortho
@enduml