@startuml
!include ../../StylesForDiagrams.puml

title COMPLEMENTARY COMPONENT DIAGRAM \n Branch: package_by_layer
rectangle domain {
    component UseCases
    component Entities

    UseCases .> Entities
}
rectangle data {
    component LocalData
    component RemoteData
}
rectangle presentation {
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI
}
component core

data ..> core
presentation ..> core
UseCases ..> core

FavoritesUI ..> UseCases
UpcomingUI ..> UseCases
UpcomingDetailUI ..> UseCases
RemoteData ..> domain
LocalData ..> domain

skinparam Linetype ortho
@enduml