@startuml
!include ../../StylesForDiagrams.puml

title EXPECTATION AND REALITY \n Branch: package_by_layer
package app as "com.vanskarner.cleanmovie"{
    class FavoritesPresenter
}
package domain as "com.vanskarner.usecases"{
    interface MovieServices<<interface>>
    class MovieDefaultServices classNotVisible
    interface MovieLocalRepository<<interface>>
    class FindUpcomingMovieUseCase classNotVisible

    MovieServices <|.. MovieDefaultServices
    MovieDefaultServices --> FindUpcomingMovieUseCase
    FindUpcomingMovieUseCase --> MovieLocalRepository
}
package entities as "com.vanskarner.entities"{
    class MovieBO
}
package localData as "com.vanskarner.localdata"{
    class MovieLocalRxRepository classNotVisible
}

FavoritesPresenter ..> MovieServices: <<use>>
FindUpcomingMovieUseCase .> MovieBO: <<use>>
MovieLocalRepository <|.. MovieLocalRxRepository

skinparam titleFontColor green
hide members
@enduml
