@startuml
!include ../../StylesForDiagrams.puml

title COMPLEMENTARY COMPONENT DIAGRAM \n Branch: package_by_layer
component Domain
interface MovieService
rectangle Data {
    component LocalData
    component RemoteData
}
rectangle "UI / Presentation" {
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI    
}
component Core

MovieService - Domain
FavoritesUI ..> MovieService
UpcomingUI ..> MovieService
UpcomingDetailUI ..> MovieService
RemoteData ..> Domain
LocalData ..> Domain
Domain ..> Core
"UI / Presentation" ..> Core
"Data" ..> Core


skinparam Linetype ortho
@enduml