@startuml
!include ../../StylesForDiagrams.puml

title COMPLEMENTARY COMPONENT DIAGRAM \n Branch: package_by_layer
rectangle "domain" {
    component useCases as "use cases"
    component entities
    interface services

    services - useCases
}
rectangle "data" {
    component localData as "local data"
    component remoteData as "remote data"
}
rectangle presentation {
    component ui
}
component core

localData ..> entities
localData ..> useCases
core <.. localData
remoteData ..> entities
remoteData ..> useCases
core <.. remoteData

core <.. ui
core <.. useCases


useCases ..> entities
ui ..> services
skinparam Linetype ortho
@enduml