@startuml
!include ../../StylesForDiagrams.puml


title COMPONENT DIAGRAM WITH MAIN \n Branch: package_by_layer
rectangle "domain" {
    component useCases as "use cases"
    component entities
}
rectangle "data" {
    component localData as "local data"
    component remoteData as "remote data"
}
rectangle presentation {
    component ui
}
component main

main ..> ui
main ..> useCases
main ..> localData
main ..> remoteData

useCases .> entities
useCases <.. localData
useCases <.. remoteData

entities <.. localData
entities <.. remoteData

ui ..> useCases
skinparam Linetype ortho
@enduml