@startuml
!include ../../StylesForDiagrams.puml

title EXPECTATION AND REALITY
package app{
    class FavoritesPresenter
}
package domain{
    interface MovieServices<<interface>>
    class MovieDefaultServices classNotVisible
    interface MovieLocalRepository<<interface>>
    class FindFavoriteMovieUseCase classNotVisible

    MovieServices <|.. MovieDefaultServices
    MovieDefaultServices --> FindFavoriteMovieUseCase
    FindFavoriteMovieUseCase --> MovieLocalRepository
}
package localData{
    class MovieLocalRxRepository classNotVisible
}

FavoritesPresenter ..> MovieServices: <<use>>
MovieLocalRepository <|.. MovieLocalRxRepository

skinparam titleFontColor green
hide members
@enduml
