@startuml
!include ../../StylesForDiagrams.puml

title EXPOSURE OF USE CASE SERVICES\n Branch: package_by_layer

interface MovieServices<<interface>>
class MovieDetailDS<<(D,orange)Data Structure>>
class MovieDS<<(D,orange)Data Structure>>
class MoviesDS<<(D,orange)Data Structure>>
class MoviesFilterDS<<(D,orange)Data Structure>>
abstract DomainError<<abstract>>
class MovieFavoriteLimit
abstract class RemoteError<<abstract>>
class Unauthorised
class NotFound
class Server
class ServiceUnavailable
class NoInternet

MovieServices ..> MoviesDS
MovieServices ..> MovieDetailDS
MovieServices ..> MoviesFilterDS
MoviesDS --> "0..*" MovieDS
MoviesFilterDS --> "0..*" MovieDS
MoviesFilterDS --> "0..*" MovieDS
DomainError <|-- MovieFavoriteLimit
RemoteError <|-- NoInternet
RemoteError <|-- NotFound
RemoteError <|-- Server
RemoteError <|-- ServiceUnavailable
RemoteError <|-- Unauthorised

hide members
@enduml