@startuml
!include ../../VanskarnerStyle.puml
<style>
    caption {
    FontColor red
    FontSize 18
    FontStyle bold
    }
</style>

rectangle "INTERFACE SEGREGATION PRINCIPLE"{
    interface Repository<<interface>>{
        + getLocalItems(): List<Item>
        + getRemoteItems(): List<Item>
    }
    class RemoteRepository{
        + RemoteRepository(...)
        + getLocalItems(): List<Item>
        + getRemoteItems(): List<Item>
    }
    class LocalRepository{
        + LocalRepository(...)
        + getLocalItems(): List<Item>
        + getRemoteItems(): List<Item>
    }
    note top of RemoteRepository: method getLocalItems is not supported here.
    note top of LocalRepository: method getRemoteItems is not supported here
}

RemoteRepository ..|> Repository
LocalRepository ..|> Repository

caption INCORRECT
hide class attributes
@enduml