@startuml
!include ../../VanskarnerStyle.puml
<style>
    caption {
    FontColor green
    FontSize 18
    FontStyle bold
    }
</style>

rectangle "LISKOV’S SUBSTITUTION PRINCIPLE" {
class Billing
interface Fee<<interface>>{
    + calculate(): double
}
class NormalFee{
    - description: Description
    - price: double
    - period: Period
    + NormalFee(...)
    + calculate(): double
}
class CorporateFee{
    - description: Description
    - specialPrice: SpecialPrice
    - period: Period
    - usersQuantity: int
    - extra: Extra
    + CorporateFee(...)
    + calculate(): double
}
}
caption CORRECT

Billing -> Fee
Fee <|.. NormalFee
Fee <|.. CorporateFee

hide Billing members
@enduml