@startuml
!include ../../VanskarnerStyle.puml
<style>
    caption {
    FontColor green
    FontSize 18
    FontStyle bold
    }
</style>

rectangle "OPEN-CLOSED PRINCIPLE" {
    class IPhone{
        - processor: Processor
        - os: OS
        - connectivity: Connectivity
        - memoryRam: RAM
        - model: Model
        + IPhone(...)
        + setSpecification(Model)
    }
    interface Model<<interface>>{
        + showSpecs(): String
    }
    class Plus{
        + Plus(...)
        + showSpecs(): String
    }
    class Pro{
        + Pro(...)
        + showSpecs(): String
    }
}
caption CORRECT

IPhone -> Model
Model <|.. Plus
Model <|.. Pro

hide Plus attributes
hide Pro attributes
@enduml