@startuml
!include ../../../VanskarnerStyle.puml

rectangle "PACKAGE BY LAYER" {
    package app{
        class MoviePresenter
    }
    package domain{
        interface MovieServices<<interface>>
        class MovieDefaultServices classNotVisible
        interface MovieRepository<<interface>>

        MovieServices <|.. MovieDefaultServices
        MovieDefaultServices --> MovieRepository
    }
    package data{
        class MovieDefaultRepository classNotVisible
    }
}

MoviePresenter ..> MovieServices: <<use>>
MovieRepository <|.. MovieDefaultRepository

hide members
@enduml
