@startuml
!include ../../VanskarnerStyle.puml

rectangle "PACKAGE BY LAYER - STRICT" {
    package app{
        class MovieController
    }
    package service{
        interface MovieServices<<interface>>
        class MovieDefaultServices classNotVisible

        MovieServices <|.. MovieDefaultServices
    }
    package data{
        interface MovieRepository<<interface>>
        class MovieDefaultRepository classNotVisible

        MovieRepository <|.. MovieDefaultRepository
    }
}

MovieController ..> MovieServices: <<use>>
MovieDefaultServices ..> MovieRepository: <<use>>

hide members
@enduml