@startuml
!include ../../../StylesForDiagrams.puml

rectangle "PACKAGE PER FEATURE" {
    package app{
        class MoviePresenter
        interface MovieServices<<interface>> classNotVisible
        class MovieDefaultServices classNotVisible
        interface MovieRepository<<interface>> classNotVisible
        class MovieDefaultRepository classNotVisible

        MovieServices <|.. MovieDefaultServices
        MovieRepository <|.. MovieDefaultRepository
    }
}

MoviePresenter --> MovieServices
MovieDefaultServices --> MovieRepository

hide members
@enduml
