@startuml
!include ../../../VanskarnerStyle.puml

rectangle "DEPENDENCIES SHOWING INTERFACES" {
    component Order
    component Product
    component Account
    interface OrderServices
    interface ProductServices
    interface AccountServices
}

AccountServices -- Account
ProductServices - Product
OrderServices -- Order
Order .> ProductServices
Order ..> AccountServices
@enduml