@startuml
!include ../../../StylesForDiagrams.puml
allowmixing

rectangle {
    component User {
        interface UserRemoteRepository<<interface>>
        interface UserLocalRepository<<interface>>
        interface UserServices<<interface>>
        class DefaultUserServices
        class CommentPostUseCase
        class UpdateInfoUseCase

        UserServices <|.. DefaultUserServices
        DefaultUserServices --> CommentPostUseCase
        DefaultUserServices -> UpdateInfoUseCase
        UserLocalRepository <-- UpdateInfoUseCase
        UserRemoteRepository <-- UpdateInfoUseCase
    }
    component Presentation {
        class Presenter
        class CustomView
        interface ContractView<<interface>>

        CustomView .|> ContractView
        ContractView <- Presenter
    }
    component Persistence {
        class CustomUserRemoteRepository
        class CustomUserLocalRepository
        class CustomPublicationRemoteRepository
    }
    component Publication {
        interface PublicationServices<<interface>>
        interface PublicationRemoteRepository<<interface>>
        class DefaultPublicationServices
        class AddCommentUseCase

        PublicationServices <|. DefaultPublicationServices
        DefaultPublicationServices --> AddCommentUseCase
        AddCommentUseCase -> PublicationRemoteRepository
    }
}

Presenter ..> UserServices
CommentPostUseCase ..> PublicationServices
CustomUserRemoteRepository ..|> UserRemoteRepository
CustomUserLocalRepository ..|> UserLocalRepository
CustomPublicationRemoteRepository ..|> PublicationRemoteRepository

skinparam Linetype ortho
hide members
skinparam packageBackgroundColor white
@enduml