@startuml
'https://plantuml.com/component-diagram

caption "Any software system has both stable and unstable components."

rectangle "USER IS A COMPONENT STABLE\n (Component difficult to change)" {
    component User
    component Presentation
    component Persistence
    component Authentication

    Presentation ..> User
    Persistence ..> User
    Authentication ..> User
}

rectangle "PROJECTS IS A COMPONENT UNSTABLE\n (Volatile component)" {
    component Projects
    component Tasks
    component Resources
    component Calendar

    Projects ..> Tasks
    Projects ..> Resources
    Projects ..> Calendar
}

skinparam Linetype ortho
@enduml