@startuml
!include ../../../VanskarnerStyle.puml

rectangle GENERALIZATION{
    abstract Vehicle<<abstract>>
    class Car
    class Motorcycle
    note "'is a type of'" as N3
}

Vehicle <|- Car
Vehicle <|-- Motorcycle

hide members
@enduml