@startuml
!include ../../VanskarnerStyle.puml

rectangle "EXAMPLE OF DATA STRUCTURES" {
    class Data1<<(D,orange)Data Structure>>{
        + anyString: String
        + anyInt: int
        + anyFloat: float
        + anyDouble: double
        + anyLong: long
        + anyBoolean: boolean
        + anyList: List<String>
        + Data1(String,int,float,double,long,boolean,List<String>)
    }
    class Data2<<(D,orange)Data Structure>>{
        + anyString: String
        + anyInt: int
        + anyFloat: float
        + anyDouble: double
        + anyLong: long
        + anyBoolean: boolean
        + anyList: List<String>
        + Data1(String,int,float,double,long,boolean,List<String>)
        + {static} empty(): Data2
    }
    class Data3<<(D,orange)Data Structure>>{
        + anyString: String = " "
        + anyInt: int
        + anyFloat: float
        + anyDouble: double
        + anyLong: long
        + anyBoolean: boolean
        + anyList: List<String> = Collections.emptyList
    }
    class Data4<<(D,orange)Data Structure>>{
        - anyString: String
        - anyInt: int
        - anyFloat: float
        - anyDouble: double
        - anyLong: long
        - anyBoolean: boolean
        - anyList: List<String>
        + Data4(String,int,float,double,long,boolean,List<String>)
        + getAnyString(): String
        + setAnyString(String): void
        + getAnyInt(): int
        + setAnyInt(int): void
        + getAnyFloat(): float
        + setAnyFloat(float): void
        + getAnyDouble(): double
        + setAnyDouble(double): void
        + getAnyLong(): long
        + setAnyLong(long): void
        + isAnyBoolean(): boolean
        + setAnyBoolean(boolean): void
        + getAnyList(): List<String>
        + setAnyList(List<String>): void
    }
}

hide Data3 methods
@enduml