@startuml
!include ../../StylesForDiagrams.puml

title COMPLEMENTARY COMPONENT DIAGRAM \n Branch: package_by_component

component ui
component core
component movie
interface services

ui ..> services
services - movie
core <.. ui
core <.. movie
@enduml