@startuml
!include ../../StylesForDiagrams.puml

title COMPLEMENTARY COMPONENT DIAGRAM \n Branch: package_by_component

rectangle "UI / Presentation" {
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI
}

component Core
component Movie
interface services

FavoritesUI ..> services
UpcomingUI ..> services
UpcomingDetailUI .> services
services -- Movie
Movie ..> Core
"UI / Presentation" ..> Core

skinparam Linetype ortho
@enduml