@startuml
!include ../../StylesForDiagrams.puml

title COMPONENT DIAGRAM
component core
component movie #white{
    component localpersistence as "local persistence"
    component remotepersistence as "remote persistence"
    component businesslogic as "business logic"

    businesslogic <.. remotepersistence
    businesslogic <.. localpersistence
}
component app

core <.. movie
core <.. app
movie <.left. app
@enduml