@startuml
!include ../../StylesForDiagrams.puml

title COMPLEMENTARY COMPONENT DIAGRAM \n Branch: package_by_component

component FavoritesUI
component UpcomingUI
component UpcomingDetailUI
component Core
component Movie
interface services

FavoritesUI ..> services
UpcomingUI ..> services
UpcomingDetailUI ..> services
services -- Movie
Movie ..> Core

skinparam Linetype ortho
@enduml