@startuml
!include ../../StylesForDiagrams.puml

title COMPONENT DIAGRAM WITH Main \n Branch: package_by_component
component Core
component Movie
component FavoritesUI
component UpcomingUI
component UpcomingDetailUI
component Main

Main ..> FavoritesUI
Main ..> UpcomingUI
Main ..> UpcomingDetailUI
Main ..> Movie
Main ..> Core
FavoritesUI ..> Movie
UpcomingUI ..> Movie
UpcomingDetailUI ..> Movie
Movie ..> Core

skinparam Linetype ortho
@enduml