@startuml
!include ../../StylesForDiagrams.puml

title COMPONENT DIAGRAM \n Branch: package_by_component
component core
component movie #white{
    component localpersistence as "local persistence"
    component remotepersistence as "remote persistence"
    component businesslogic as "business logic"

    businesslogic <.. remotepersistence
    businesslogic <.. localpersistence
}
component ui

core <.. movie
core <.. ui
ui ..> movie
@enduml