@startuml
!include ../../StylesForDiagrams.puml

title COMPONENT DIAGRAM WITH Main \n Branch: package_by_component
component Core
component Movie
rectangle presentation {
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI
}
component Main

Main ..> presentation
Main ..> Movie
Main ..> Core
FavoritesUI ..> Movie
UpcomingUI ..> Movie
UpcomingDetailUI ..> Movie
Movie ..> Core
presentation ..> Core

skinparam Linetype ortho
@enduml