@startmindmap

title Main Component Configuration
* :app
** AppComponent
*** ProjectParametersModule
*** RoomDBModule
*** :core
**** CoreModule
*** :movie
**** MovieModule
***** MovieBusinessLogicModule
****** MovieErrorModule
***** MovieLocalRepositoryModule
***** MovieRemoteRepositoryModule
****** MovieRemoteErrorsModule
*** ViewModule
**** AndroidInjectionModule
**** FragmentBuildersModule
***** FavoritesModule
***** UpcomingModule
***** UpcomingDetailModule
**** ViewErrorTypesModule
legend
It establishes the initial conditions and configurations
end legend

skinparam legendBackgroundColor #FEFECE
@endmindmap