@startuml
!include ../../StylesForDiagrams.puml

title MOVIE COMPONENT SERVICE EXPOSURE \n Branch: package_by_component

interface MovieServices<<interface>>
class MovieDetailDS<<(D,orange)Data Structure>>
class MovieBasicDS<<(D,orange)Data Structure>>
class MoviesDS<<(D,orange)Data Structure>>
class MoviesFilterDS<<(D,orange)Data Structure>>
exception MovieError<<abstract>>
exception FavoriteLimitError
exception MovieRemoteError<<abstract>>
exception Unauthorised
exception NotFound
exception Server
exception ServiceUnavailable
exception NoInternet

MovieServices ..> MoviesDS
MovieServices ..> MovieDetailDS
MovieServices ..> MoviesFilterDS
MovieDetailDS --> MovieBasicDS
MoviesDS --> "0..*" MovieBasicDS
MoviesFilterDS --> "0..*" MovieBasicDS
MoviesFilterDS --> "0..*" MovieBasicDS
MovieError <|-- FavoriteLimitError
MovieRemoteError <|-- NoInternet
MovieRemoteError <|-- NotFound
MovieRemoteError <|-- Server
MovieRemoteError <|-- ServiceUnavailable
MovieRemoteError <|-- Unauthorised

hide members
@enduml