@startuml
!include ../../../../../../../../StylesForDiagrams.puml

/'Specification'/
package core as "com.vanskarner.core"{
    package sync{
        interface Result<T><<interface>>
    }
    package concurrent{
        interface FutureResult<T><<interface>>
        interface FutureSimpleResult<<interface>>
        package rxjava{
        interface RxFutureFactory<<interface>>
        }
    }
}
package movie as "com.vanskarner.movie"{
    package businesslogic {
        interface MovieServices<<interface>>
        interface MovieLocalRepository<<interface>>
        interface MovieRemoteRepository<<interface>>
    }
    package persistence.local {
        class MovieLocalRxRepository
    }
    package persistence.remote {
        class MovieRemoteRxRepository
    }
}

/'Relations'/
FutureResult <.. MovieServices: <<use>>
Result <.. MovieServices: <<use>>
RxFutureFactory <.. MovieLocalRxRepository: <<use>>
RxFutureFactory <.. MovieRemoteRxRepository: <<use>>
FutureSimpleResult <.. MovieLocalRepository: <<use>>
FutureResult <.. MovieLocalRepository: <<use>>
FutureResult <.. MovieRemoteRepository: <<use>>

/'Visualization'/
hide members
skinparam LineType ortho
@enduml