@startuml
!include ../../../../../../../../StylesForDiagrams.puml

/'Specification'/
package core as "com.vanskarner.core"{
    interface Result<T><<interface>>
    interface FutureResult<T><<interface>>
}
package movie as "com.vanskarner.movie"{
    package businesslogic {
        class MovieDetailDS<<(D,orange)Data Structure>>
        class MovieDS<<(D,orange)Data Structure>>
        class MoviesDS<<(D,orange)Data Structure>>
        class MoviesFilterDS<<(D,orange)Data Structure>>
        interface MovieServices<<interface>>
        class MovieDefaultServices
        class FilterUpcomingMoviesUseCase
        class ToggleMovieFavoriteUseCase
        class CheckFavoriteMovieUseCase
        class DeleteAllFavoriteMoviesUseCase
        class FindFavoriteMovieUseCase
        class ShowFavoriteMoviesUseCase
        class ShowUpcomingMoviesUseCase
        class FindUpcomingMovieUseCase
        together {
            interface MovieLocalRepository<<interface>>
            interface MovieRemoteRepository<<interface>>
        }
        class MovieMapper
        together {
            class MovieErrorFilter
            abstract MovieError<<abstract>>
            class FavoriteLimit
        }
        entity MovieBO
    }
    package persistence.local{
        interface MovieDao<<interface>>
        class MovieEntity<<(D,orange)Data Structure>>
        class MovieLocalRxRepository
        class MovieLocalDataMapper
    }
    package persistence.remote{
        class MovieRemoteRxRepository
        class MovieDeserializer
        class MovieDTO<<(D,orange)Data Structure>>
        class MovieRemoteDataMapper
        interface MovieApiClient<<interface>>
        class MoviesResultDTO<<(D,orange)Data Structure>>
        class RemoteDataErrorFilter
        abstract class MovieRemoteError<<abstract>>
        class Unauthorised
        class NotFound
        class Server
        class ServiceUnavailable
        class NoInternet
        class MovieRemoteErrorInterceptor
    }
}

/'Relations'/
MovieServices ..> MoviesDS
MovieServices ..> MovieDetailDS
MovieServices ..> MoviesFilterDS
MoviesDS --> "0..*" MovieDS
MoviesFilterDS --> "0..*" MovieDS
MoviesFilterDS --> "0..*" MovieDS

MovieDefaultServices .left.|> MovieServices
MovieDefaultServices --> ShowUpcomingMoviesUseCase
MovieDefaultServices --> FindUpcomingMovieUseCase
MovieDefaultServices --> ShowFavoriteMoviesUseCase
MovieDefaultServices --> FindFavoriteMovieUseCase
MovieDefaultServices --> CheckFavoriteMovieUseCase
MovieDefaultServices --> ToggleMovieFavoriteUseCase
MovieDefaultServices --> DeleteAllFavoriteMoviesUseCase
MovieDefaultServices --> FilterUpcomingMoviesUseCase

CheckFavoriteMovieUseCase --> MovieLocalRepository
ToggleMovieFavoriteUseCase --> MovieLocalRepository
DeleteAllFavoriteMoviesUseCase --> MovieLocalRepository
FindFavoriteMovieUseCase --> MovieLocalRepository
ShowFavoriteMoviesUseCase --> MovieLocalRepository
ShowUpcomingMoviesUseCase --> MovieRemoteRepository
FindUpcomingMovieUseCase --> MovieRemoteRepository

ShowUpcomingMoviesUseCase ..> MovieMapper
FindUpcomingMovieUseCase ..> MovieMapper
ShowFavoriteMoviesUseCase ..> MovieMapper
FindFavoriteMovieUseCase ..> MovieMapper

MovieMapper ..> MovieDetailDS
MovieMapper ..> MovieBO
MovieMapper ..> MoviesDS

ToggleMovieFavoriteUseCase --> MovieErrorFilter
MovieErrorFilter --> "1..*" MovieError
MovieError <|- FavoriteLimit

MovieLocalRepository ..> MovieBO
MovieRemoteRepository ..> MovieBO
/'Relations - local-data:start'/
MovieLocalRxRepository --> MovieDao
MovieDao ..> MovieEntity
MovieLocalRxRepository ..> MovieLocalDataMapper
MovieLocalDataMapper ..> MovieEntity
MovieLocalDataMapper ..> MovieBO
MovieLocalRxRepository ..|> MovieLocalRepository
/'Relations - local-data:end'/

/'Relations - remote-data:start'/
MovieRemoteRxRepository ..|> MovieRemoteRepository
MovieRemoteRxRepository --> MovieApiClient
MovieRemoteRxRepository ..> MovieRemoteDataMapper
MovieApiClient ..> MovieDTO
MovieApiClient ..> MoviesResultDTO
MovieRemoteDataMapper ..> MovieDTO
MovieRemoteDataMapper ..> MovieBO
MovieDeserializer ..> MovieDTO
MoviesResultDTO -> "0..*" MovieDTO
RemoteDataErrorFilter --> "1..*" MovieRemoteError
RemoteDataErrorFilter --> "1" MovieRemoteError
MovieRemoteError <|-- NoInternet
MovieRemoteError <|-- NotFound
MovieRemoteError <|-- Server
MovieRemoteError <|-- ServiceUnavailable
MovieRemoteError <|-- Unauthorised
MovieRemoteErrorInterceptor --> RemoteDataErrorFilter
/'Relations - remote-data:end'/
Result <.. MovieServices
FutureResult <.. MovieServices

/'Visualization'/
hide members
skinparam LineType ortho
@enduml