@startuml
!include ../../VanskarnerStyle.puml

rectangle DEPENDENCY{
    class Printer{
        + Printer(...)
        +print(Document):void
        +generateReport():StatusReport
        +doMaintenance():void
    }
    class Document
    class StatusReport
    class TestPrint
    note "'use'" as N2

}

Printer .> Document
Printer ..> StatusReport
Printer ..> TestPrint

hide Printer attributes
hide StatusReport members
hide TestPrint members
hide Document members
@enduml