@startuml
!include ../../../StylesForDiagrams.puml

rectangle "PACKAGE PER COMPONENT"{
    package app{
        class MoviePresenter
    }
    package movie{
        interface MovieServices<<interface>>
        class MovieDefaultServices classNotVisible
        interface MovieRepository<<interface>> classNotVisible
        class MovieDefaultRepository classNotVisible

        MovieServices <|.. MovieDefaultServices
        MovieRepository <|.. MovieDefaultRepository
    }
}

MoviePresenter ..> MovieServices: <<use>>
MovieDefaultServices --> MovieRepository

hide members
@enduml