@startuml
!include ../../VanskarnerStyle.puml
allowmixing

title "VIOLATION OF THE PRINCIPLE OF ACYCLIC DEPENDENCIES"
rectangle "Component Dependency"{
    component Main
    component Presentation
    component Persistence
    component User
    component Authorization
    component "Image Analysis"
}

Main ..> Presentation
Main ..> Persistence
Main ..> User
Main ..> Authorization
Main ..> "Image Analysis"
Presentation ..> User
Persistence ..> User
User <. Authorization #red
Authorization <.. "Image Analysis" #red
"Image Analysis" <.. User #red

skinparam titleFontColor #red
skinparam Linetype ortho
@enduml