@startuml
!include ../../VanskarnerStyle.puml
allowmixing
title "PRINCIPLE OF ACYCLIC DEPENDENCIES\n APPLYING DEPENDENCY INVERSION"

rectangle "Component Dependency"{
    component Main
    component Presentation
    component Persistence
    component User
    component Authorization
    component "Project"
}
rectangle "Dependency Inversion"{
    component Authorization as AuthorizationOther{
        class CustomPermissions
    }
    component "Project" as ImageAnalysis{
        class CustomProject
        interface Permissions<<interface>>
    }
    CustomPermissions ..|> Permissions
    CustomProject -> Permissions
}

Main ..> Presentation
Main ..> Persistence
Main ..> User
Main ..> Authorization
Main ..> "Project"
Presentation ..> User
Persistence ..> User

User <. Authorization
Authorization ..> "Project"
"Project" <.. User

skinparam Linetype ortho
skinparam titleFontColor #GREEN
skinparam packageBackgroundColor #white
hide members
@enduml