@startuml
!include ../VanskarnerStyle.puml

together {

    rectangle "Technical Infrastructure" as R1{
        class CustomView
        class CustomRepository
    }

    rectangle "Interface Adapters" {
        interface ViewContract<<interface>>
        interface PresenterContract<<interface>>
        class Presenter
        class Mapper
        class Model<<(D,orange)Data Structure>>

        ViewContract <-- Presenter
        PresenterContract <|.. Presenter
        Mapper <.. Presenter
        Mapper ..> Model

        Model <.. ViewContract
        Model <.. PresenterContract
    }
}

together {
    rectangle "Application Business Rules" {
        class UseCase
        class InputData<<(D,orange)Data Structure>>
        class OutputData<<(D,orange)Data Structure>>
        interface Repository<<interface>>
        interface Services<<interface>>
        class DefaultServices

        InputData <.. Services
        OutputData <.. Services
        UseCase --> Repository
        Services <|.. DefaultServices
        DefaultServices --> UseCase
    }
    rectangle "Enterprise Business Rules" {
        entity Entitiy
    }
    UseCase --> Entitiy
}

Mapper ..> InputData
Mapper ..> OutputData
CustomView .|> ViewContract
Presenter -> Services
CustomRepository .|> Repository

hide members
skinparam Linetype ortho
@enduml