@startuml
!include ../../../StylesForDiagrams.puml

rectangle "MAPPER"{
    class TypeA
    class TypeB
    class Mapper{
        -Mapper()
        +{static} convert(TypeA): TypeB
    }
}

Mapper ..> TypeA
Mapper ..> TypeB

hide Mapper attributes
hide TypeA members
hide TypeB members
@enduml