@startuml
!include ../../../../../../../StylesForDiagrams.puml

/'Specification'/
package usecases as "com.vanskarner.domain"{

package movie {
    class MovieDefaultServices
    abstract UseCase<Output,Input><<abstract>>
    class MovieUseCaseFilter
    class FilterUpcomingMoviesUseCase
    class ToggleMovieFavoriteUseCase
    class CheckFavoriteMovieUseCase
    class DeleteAllFavoriteMoviesUseCase
    class FindFavoriteMovieUseCase
    class ShowFavoriteMoviesUseCase
    class ShowUpcomingMoviesUseCase
    class FindUpcomingMovieUseCase
    entity MovieBO
    class MovieMapper
    together {
        class MovieErrorFilter
        exception MovieError<<abstract>>
        exception FavoriteLimitError

        ToggleMovieFavoriteUseCase --> MovieErrorFilter
        MovieErrorFilter --> "1..*" MovieError
        MovieError <|-- FavoriteLimitError
    }
    together {
        interface MovieServices<<interface>>
        class MovieDetailDS<<(D,orange)Data Structure>>
        class MovieBasicDS<<(D,orange)Data Structure>>
        class MoviesDS<<(D,orange)Data Structure>>
        class MoviesFilterDS<<(D,orange)Data Structure>>

        MovieServices ..> MoviesDS
        MovieServices ..> MovieDetailDS
        MovieServices ..> MoviesFilterDS
        MoviesDS --> "0..*" MovieBasicDS
        MoviesFilterDS --> "0..*" MovieBasicDS
        MoviesFilterDS --> "0..*" MovieBasicDS
        MovieDetailDS --> MovieBasicDS
    }
    together {
        interface MovieLocalRepository<<interface>>
        interface MovieRemoteRepository<<interface>>
    }
}

}

/'Relations'/
MovieDefaultServices ..|> MovieServices
MovieUseCaseFilter <- MovieDefaultServices
MovieUseCaseFilter --> "1..*" UseCase
UseCase <|-- ShowUpcomingMoviesUseCase
UseCase <|-- FindUpcomingMovieUseCase
UseCase <|-- ShowFavoriteMoviesUseCase
UseCase <|-- FindFavoriteMovieUseCase
UseCase <|-- CheckFavoriteMovieUseCase
UseCase <|-- ToggleMovieFavoriteUseCase
UseCase <|-- DeleteAllFavoriteMoviesUseCase
UseCase <|-- FilterUpcomingMoviesUseCase

CheckFavoriteMovieUseCase --> MovieLocalRepository
ToggleMovieFavoriteUseCase --> MovieLocalRepository
ToggleMovieFavoriteUseCase -> CheckFavoriteMovieUseCase
DeleteAllFavoriteMoviesUseCase --> MovieLocalRepository
FindFavoriteMovieUseCase --> MovieLocalRepository
ShowFavoriteMoviesUseCase --> MovieLocalRepository
ShowUpcomingMoviesUseCase --> MovieRemoteRepository
FindUpcomingMovieUseCase --> MovieRemoteRepository

ShowUpcomingMoviesUseCase ..> MovieMapper
FindUpcomingMovieUseCase ..> MovieMapper
ShowFavoriteMoviesUseCase ..> MovieMapper
FindFavoriteMovieUseCase ..> MovieMapper
FindUpcomingMovieUseCase ..> MovieBO

MovieMapper ..> MovieDetailDS
MovieMapper ..> MovieBO
MovieMapper ..> MoviesDS

MovieLocalRepository ..> MovieBO
MovieRemoteRepository ..> MovieBO

/'Visualization'/
hide members
skinparam LineType ortho
@enduml