@startuml
!include ../../../../../../../StylesForDiagrams.puml

/'Specification'/
package domain as "com.vanskarner.domain" {
    package movie{

    }
}

package core as "com.vanskarner.core" {
    package concurrent{
        interface FutureResult<T><<interface>>
        interface FutureSimpleResult<<interface>>
    }
    package sync{
        interface Result<T><<interface>>
    }
}
/'Relations'/
sync <.. movie: <<use>>
concurrent <... movie: <<use>>
/'Visualization'/
hide members
skinparam LineType ortho
@enduml