@startuml
!include ../../VanskarnerStyle.puml

<style>
    caption {
    FontColor red
    FontSize 18
    FontStyle bold
    }
</style>

rectangle "DEPENDENCY INVERSION PRINCIPLE" {
    package "High level politics"{
        class UseCase
        class CustomRemoteRepository

        UseCase --> CustomRemoteRepository
    }
}
caption INCORRECT

hide members
@enduml