@startuml
!include ../../../VanskarnerStyle.puml
<style>
    caption {
    FontColor red
    FontSize 18
    FontStyle bold
    }
</style>

rectangle "OPEN-CLOSED PRINCIPLE" {
    class IPhone{
        - processor: Processor
        - os: OS
        - connectivity: Connectivity
        - memoryRam: RAM
        - specification: Specification
        + IPhone(...)
        + setSpecification(Specification)
    }
    class Specification{
        - modelName: String
        - displayResolution: DisplayResolution
        - screenMetrics: ScreenMetrics
        - weight: Weight
        + Specification (...)
        + showSpecs(): String
    }
    note right of Specification
        what if a new specification comes out?
        - Modifications are coming
    end note
}
caption INCORRECT

IPhone -> Specification
@enduml