@startuml
!include ../../../VanskarnerStyle.puml
<style>
    caption {
    FontColor red
    FontSize 18
    FontStyle bold
    }
</style>

rectangle "SINGLE RESPONSIBILITY PRINCIPLE" {
    class Worker{
        - name: String
        - baseSalary: double
        - hourlyRate: HourlyRate
        - bonuses: Bonuses
        + Worker(...)
        + calculateSalary(): double
        + generateReport(): void
        ..Getter and Setter..
    }
}
caption INCORRECT
@enduml