@startuml
!include ../VanskarnerStyle.puml

title REALITY
package app{
    class FavoritesPresenter
}
package domain{
    interface MovieServices<<interface>>
    class MovieDefaultServices
    interface MovieLocalRepository<<interface>>
    class FindFavoriteMovieUseCase

    MovieServices <|.. MovieDefaultServices
    MovieDefaultServices --> FindFavoriteMovieUseCase
    FindFavoriteMovieUseCase --> MovieLocalRepository
}
package localData{
    class MovieLocalRxRepository
}

FavoritesPresenter ..> MovieServices
MovieLocalRepository <|.. MovieLocalRxRepository

skinparam titleFontColor red
class MovieDefaultServices classNotVisible
class MovieLocalRxRepository classNotVisible
class FindFavoriteMovieUseCase classNotVisible
hide members
@enduml
