@startuml
!include ../VanskarnerStyle.puml

left to right direction
title COMPONENT DIAGRAM WITH MAIN
rectangle "domain" {
    component useCases
    component entities
}
rectangle "data" {
    component localData
    component remoteData
}
rectangle presentation {
    component app
}
component main

main ..> app
main ..> useCases
main ..> remoteData
main ..> localData
useCases .> entities
useCases <.. localData
useCases <.. remoteData
entities <.. localData
entities <.. remoteData
app ..> useCases
@enduml