@startuml
!include ../../VanskarnerStyle.puml

rectangle "PACKAGE PER COMPONENT"{
    package app{
        class MoviePresenter
    }
    package movie{
        interface MovieServices<<interface>>
        class MovieDefaultServices
        interface MovieRepository<<interface>>
        class MovieDefaultRepository

        MovieServices <|.. MovieDefaultServices
        MovieRepository <|.. MovieDefaultRepository
    }
}

MoviePresenter ..> MovieServices
MovieDefaultServices --> MovieRepository

class MovieDefaultServices classNotVisible
class MovieDefaultRepository classNotVisible
interface MovieRepository classNotVisible
hide members
@enduml