@startuml
!include ../../VanskarnerStyle.puml

rectangle "PACKAGE PER LAYER" {
    package app{
        class MoviePresenter
    }
    package domain{
        interface MovieServices<<interface>>
        class MovieDefaultServices
        interface MovieRepository<<interface>>

        MovieServices <|.. MovieDefaultServices
        MovieDefaultServices --> MovieRepository
    }
    package data{
        class MovieDefaultRepository
    }
}

MoviePresenter ..> MovieServices
MovieRepository <|.. MovieDefaultRepository

class MovieDefaultServices classNotVisible
interface MovieRepository classNotVisible
class MovieDefaultRepository classNotVisible
hide members
@enduml
