@startuml
!include ../../VanskarnerStyle.puml

rectangle "PACKAGE PER LAYER - STRICT" {
    package app{
        class MoviePresenter
    }
    package domain{
        interface MovieServices<<interface>>
        class MovieDefaultServices

        MovieServices <|.. MovieDefaultServices
    }
    package data{
        interface MovieRepository<<interface>>
        class MovieDefaultRepository

        MovieRepository <|.. MovieDefaultRepository
    }
}

MoviePresenter ..> MovieServices
MovieDefaultServices ..> MovieRepository

class MovieDefaultServices classNotVisible
class MovieDefaultRepository classNotVisible
hide members
@enduml
