@startuml
!include ../../VanskarnerStyle.puml

rectangle "PORTS AND ADAPTERS" {
    package app{
        class MoviePresenter
    }
    package domain{
        interface MovieServices<<interface>>
        class MovieDefaultServices
        interface Movies<<interface>>

        MovieServices <|.. MovieDefaultServices
        MovieDefaultServices ..> Movies
    }
    package data{
        class MoviesRepository
    }
}

MoviePresenter ..> MovieServices
Movies <|.. MoviesRepository

class MovieDefaultServices classNotVisible
class MoviesRepository classNotVisible
hide members
@enduml