@startuml
!include ../VanskarnerStyle.puml

rectangle "THE MAIN COMPONENT" {
    component Main
    component UI
    component "Business Logic"
    component Persistence
}

Main ..> UI
Main ..> Persistence
Main ..> "Business Logic"
UI .> "Business Logic"
"Business Logic" <. Persistence
@enduml