@startuml
!include ../../../../../../../StylesForDiagrams.puml

/'Specification'/
package remotedata as "com.vanskarner.remotedata"{
    package movie{
        class MovieRemoteDataMapper
        class MovieRemoteRxRepository
    }
}
package domain as "com.vanskarner.domain"{
    package movieDomain as "movie"{
        entity MovieBO
        interface MovieRemoteRepository<<interface>>
    }
}
package core as "com.vanskarner.core"{
    package concurrent{
        interface FutureResult<T><<interface>>
        package rxjava{
        interface RxFutureFactory<<interface>>
        }
    }
}

/'Relations'/
FutureResult <.. MovieRemoteRxRepository: <<use>>
RxFutureFactory <.. MovieRemoteRxRepository: <<use>>
MovieRemoteRepository <|.. MovieRemoteRxRepository
MovieBO <.. MovieRemoteRxRepository: <<use>>
MovieBO <.. MovieRemoteDataMapper: <<use>>

/'Visualization'/
hide members
skinparam Linetype ortho
@enduml