@startuml
!include ../../StylesForDiagrams.puml

title COMPONENT DIAGRAM WITH Main \n Branch: package_by_feature
component Core
component Movie
component Main
rectangle AndroidView as "Android View"{
    component FavoritesView<<android>>
    component UpcomingView<<android>>
    component UpcomingDetailView<<android>>
}

FavoritesView ..> Movie
UpcomingView ..> Movie
UpcomingDetailView ..> Movie
Movie ..> Core
Main ..> AndroidView
Main .> Movie
Main ..> Core

skinparam Linetype ortho
@enduml