@startuml
!include ../../StylesForDiagrams.puml

title COMPONENT DIAGRAM WITH Main \n Branch: package_by_feature
component Core
component Movie
component Main
component AndroidView<<android>>

AndroidView ..> Movie
Movie ..> Core
Main ..> AndroidView
Main .> Movie
Main ..> Core

skinparam Linetype ortho
@enduml