@startuml
!include ../../VanskarnerStyle.puml

left to right direction
rectangle "FLOW OF CONTROL CROSSES THE BOUNDARY" {
    package "Lower Level" as LL{
        class Customer
    }
    package "Higher Level" as HL{
        interface Service <<interface>>{
            + anyService(Data): void
        }
        class CustomService
        class Data<<(D,orange)Data Structure>>

        Service <|.. CustomService
        Service .> Data
    }

    Customer .> Service: <<use>>
    Customer ..> Data: <<use>>
}

hide class members
show Service methods
@enduml