@startuml
!include ../../../VanskarnerStyle.puml

left to right direction
rectangle "CROSSING THE BOUNDARY AGAINST THE FLOW OF CONTROL"{
    package "Higher Level" as LayerA{
        class "Customer" as clientB
        interface "Service" as ServiceB<<interface>>{
            +anyService(Data): void
        }
        class "Data" as DataB<<(D,orange)Data Structure>>

        clientB --> ServiceB
        clientB --> DataB
        ServiceB .> DataB
    }
    package "Lower Level" as LayerB{
        class CustomService
    }

    ServiceB <|.. CustomService
    DataB <.. CustomService: <<use>>
}

hide class members
@enduml