@startuml
!include ../StylesForDiagrams.puml

title COMPONENT DIAGRAM WITH MAIN \n Branch: package_by_component
component Core
component Movie
rectangle "UI / Presentation" {
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI
}
component Main

Main ..> "UI / Presentation"
Main ..> Movie
Main ..> Core
FavoritesUI ..> Movie
UpcomingUI ..> Movie
UpcomingDetailUI ..> Movie
Movie ..> Core
"UI / Presentation" ..> Core

skinparam Linetype ortho
@enduml