@startuml
!include ../StylesForDiagrams.puml

title COMPONENT DIAGRAM \n Branch: package_by_layer

component Domain

rectangle Data {
    component LocalData
    component RemoteData
}
rectangle "UI / Presentation" {
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI
}
component Core

Data ..> Core
"UI / Presentation" ..> Core
Domain ..> Core
RemoteData ..> Domain
LocalData ..> Domain
FavoritesUI ..> Domain
UpcomingUI ..> Domain
UpcomingDetailUI ..> Domain

skinparam Linetype ortho
@enduml