@startuml
!include ../StylesForDiagrams.puml

title COMPONENT DIAGRAM \n Branch: package_by_feature

component Core
component Movie #white{
    component LocalPersistence
    component RemotePersistence
    component BusinessLogic
    component UI

    UI ..> BusinessLogic
    RemotePersistence ..> BusinessLogic
    LocalPersistence ..> BusinessLogic
}
component AndroidView<<android>>#LimeGreen

Movie ...> Core
AndroidView ...> Movie
@enduml