@startuml
!include ../StylesForDiagrams.puml

title COMPONENT DIAGRAM WITH MAIN\n Branch: package_by_layer
component Main
component Domain
rectangle Data {
    component LocalData
    component RemoteData
}
rectangle "UI / Presentation" {
    component FavoritesUI
    component UpcomingUI
    component UpcomingDetailUI
}
component Core

Main ..> Data
Main ..> "UI / Presentation"
Main ..> Domain
Main .> Core
RemoteData ..> Domain
LocalData ..> Domain
FavoritesUI ..> Domain
UpcomingUI ..> Domain
UpcomingDetailUI ..> Domain
Data ..> Core
"UI / Presentation" ..> Core
Domain ..> Core


skinparam Linetype ortho
@enduml