@startuml
!include ../StylesForDiagrams.puml

title MOVIE COMPONENT SERVICE EXPOSURE  \n Branch: package_by_feature

interface FavoritesContractPresenter<<interface>>
interface UpcomingContractPresenter<<interface>>
interface UpcomingDetailContractPresenter<<interface>>
interface FavoritesContractView<<interface>>
interface UpcomingContractView<<interface>>
interface UpcomingDetailContractView<<interface>>
class MovieDetailDS<<(D,orange)Data Structure>>
class MovieBasicDS<<(D,orange)Data Structure>>
exception MovieError<<abstract>>
exception FavoriteLimitError
exception MovieRemoteError<<abstract>>
exception Unauthorised
exception NotFound
exception Server
exception ServiceUnavailable
exception NoInternet

FavoritesContractView ..> MovieDetailDS
FavoritesContractView ..> MovieBasicDS
UpcomingContractView ..> MovieBasicDS
UpcomingDetailContractView ..> MovieDetailDS
UpcomingDetailContractPresenter ..> MovieDetailDS
MovieError <|-- FavoriteLimitError
MovieRemoteError <|-- NoInternet
MovieRemoteError <|-- NotFound
MovieRemoteError <|-- Server
MovieRemoteError <|-- ServiceUnavailable
MovieRemoteError <|-- Unauthorised

hide members
@enduml